version: '3'
services:
  nginx:
    build: ./nginx
    restart: always
    ports:
      - "80:8000"
    volumes:
      - tmp:/tmp
      - ethermill-vol:/static
    depends_on:
      - web
  web:
    build: ./ethermill
    restart: always
    volumes:
      - tmp:/tmp
      - ethermill-vol:/code/ethermill/static
    depends_on:
      - helper
  helper:
    image: busybox:latest
    volumes:
      - tmp:/tmp
      - ethermill-vol:/static
    command: rm -rf /tmp/* && rm -rf /static/*


volumes:
    ethermill-vol:
    tmp:
