version: '3'
services:
  nginx:
    build: ./nginx
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - tmp:/tmp
      - ethermill-vol:/static
      - certs:/etc/letsencrypt
      - certs-data:/data/letsencrypt
    depends_on:
      - web
  web:
    build: ./ethermill
    restart: always
    volumes:
      - tmp:/tmp
      - ethermill-vol:/code/ethermill/static
    depends_on:
      - helper
  helper:
    image: busybox:latest
    volumes:
      - tmp:/tmp
      - ethermill-vol:/static
    command: rm -rf /tmp/* && rm -rf /static/*


volumes:
    ethermill-vol:
    tmp:
    certs:
    certs-data:
